/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import dao.ReporteDAO;
import dto.EstadisticaGlobalDTO;
import dto.UsuarioSesionDTO;

/**
 *
 * @author aguil
 */
public class EstadisticasGlobalesFrame extends javax.swing.JFrame {

    private final UsuarioSesionDTO sesion;
    private final ReporteDAO reporteDAO = new ReporteDAO();

    /**
     * Creates new form EstadisticasGlobalesFrame
     */
    public EstadisticasGlobalesFrame(UsuarioSesionDTO sesion) {
        this.sesion = sesion;
        initComponents();
        setLocationRelativeTo(null);
        inicializarVista();
    }

    private EstadisticasGlobalesFrame() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void inicializarVista() {
        lblTitulo.setText("Super Admin - Estadísticas Globales");
        lblAdmin.setText("Usuario: " + sesion.getNickname());
        cargarEstadisticas();
    }

    private void cargarEstadisticas() {
        EstadisticaGlobalDTO dto = reporteDAO.obtenerEstadisticasGlobales();

        lblTotalPartidas.setText("Total partidas: " + dto.getTotalPartidas());
        lblMejorPuntajeGlobal.setText("Mejor puntaje global: " + dto.getMejorPuntajeGlobal());
        lblPromedioPuntajeGlobal.setText("Promedio puntaje global: " + String.format("%.2f", dto.getPromedioPuntajeGlobal()));
        lblTotalEntregados.setText("Pedidos entregados: " + dto.getTotalEntregados());
        lblTotalCancelados.setText("Pedidos cancelados: " + dto.getTotalCancelados());
        lblTotalNoEntregados.setText("Pedidos no entregados: " + dto.getTotalNoEntregados());
        lblTotalJugadores.setText("Total jugadores: " + dto.getTotalJugadores());
        lblTotalAdminsTienda.setText("Total admins tienda: " + dto.getTotalAdminsTienda());
        lblTotalSucursales.setText("Total sucursales: " + dto.getTotalSucursales());
        lblEstado.setText("Estado: estadísticas cargadas");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblAdmin = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblTotalPartidas = new javax.swing.JLabel();
        lblMejorPuntajeGlobal = new javax.swing.JLabel();
        lblPromedioPuntajeGlobal = new javax.swing.JLabel();
        lblTotalEntregados = new javax.swing.JLabel();
        lblTotalCancelados = new javax.swing.JLabel();
        lblTotalNoEntregados = new javax.swing.JLabel();
        lblTotalJugadores = new javax.swing.JLabel();
        lblTotalAdminsTienda = new javax.swing.JLabel();
        lblTotalSucursales = new javax.swing.JLabel();
        btnRefrescarEstadisticasGlobales = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setText("Titulo");

        lblAdmin.setText("Admin");

        lblEstado.setText("Estado");

        lblTotalPartidas.setText("Total Partidas");

        lblMejorPuntajeGlobal.setText("Mejor Puntaje Global");

        lblPromedioPuntajeGlobal.setText("Promedio Puntaje Global");

        lblTotalEntregados.setText("Total Entregados");

        lblTotalCancelados.setText("Total Cancelados");

        lblTotalNoEntregados.setText("Total No Entregados");

        lblTotalJugadores.setText("Total Jugadores");

        lblTotalAdminsTienda.setText("Total Admins Tienda");

        lblTotalSucursales.setText("Total Sucursales");

        btnRefrescarEstadisticasGlobales.setText("Refrescar ");
        btnRefrescarEstadisticasGlobales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescarEstadisticasGlobalesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEstado)
                            .addComponent(lblTotalPartidas)
                            .addComponent(lblMejorPuntajeGlobal)
                            .addComponent(lblPromedioPuntajeGlobal)
                            .addComponent(lblTotalEntregados)
                            .addComponent(lblTotalCancelados)
                            .addComponent(lblTotalNoEntregados)
                            .addComponent(lblTotalJugadores)
                            .addComponent(lblTotalAdminsTienda)
                            .addComponent(lblTotalSucursales)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAdmin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 493, Short.MAX_VALUE)
                                .addComponent(btnRefrescarEstadisticasGlobales)))))
                .addGap(152, 152, 152))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdmin)
                    .addComponent(btnRefrescarEstadisticasGlobales))
                .addGap(18, 18, 18)
                .addComponent(lblEstado)
                .addGap(18, 18, 18)
                .addComponent(lblTotalPartidas)
                .addGap(18, 18, 18)
                .addComponent(lblMejorPuntajeGlobal)
                .addGap(18, 18, 18)
                .addComponent(lblPromedioPuntajeGlobal)
                .addGap(18, 18, 18)
                .addComponent(lblTotalEntregados)
                .addGap(18, 18, 18)
                .addComponent(lblTotalCancelados)
                .addGap(18, 18, 18)
                .addComponent(lblTotalNoEntregados)
                .addGap(18, 18, 18)
                .addComponent(lblTotalJugadores)
                .addGap(18, 18, 18)
                .addComponent(lblTotalAdminsTienda)
                .addGap(18, 18, 18)
                .addComponent(lblTotalSucursales)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefrescarEstadisticasGlobalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarEstadisticasGlobalesActionPerformed

        cargarEstadisticas();

    }//GEN-LAST:event_btnRefrescarEstadisticasGlobalesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstadisticasGlobalesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstadisticasGlobalesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstadisticasGlobalesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstadisticasGlobalesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstadisticasGlobalesFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefrescarEstadisticasGlobales;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblMejorPuntajeGlobal;
    private javax.swing.JLabel lblPromedioPuntajeGlobal;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTotalAdminsTienda;
    private javax.swing.JLabel lblTotalCancelados;
    private javax.swing.JLabel lblTotalEntregados;
    private javax.swing.JLabel lblTotalJugadores;
    private javax.swing.JLabel lblTotalNoEntregados;
    private javax.swing.JLabel lblTotalPartidas;
    private javax.swing.JLabel lblTotalSucursales;
    // End of variables declaration//GEN-END:variables
}
