/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import dao.ParametroJuegoDAO;
import dto.UsuarioSesionDTO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.ParametroJuego;

/**
 *
 * @author aguil
 */
public class GestionParametrosFrame extends javax.swing.JFrame {

    private final UsuarioSesionDTO sesion;
    private final ParametroJuegoDAO parametroJuegoDAO = new ParametroJuegoDAO();

    private DefaultTableModel modeloTabla;
    private Integer nivelSeleccionado = null;

    /**
     * Creates new form GestionParametrosFrame
     */
    public GestionParametrosFrame(UsuarioSesionDTO sesion) {
        this.sesion = sesion;
        initComponents();
        setLocationRelativeTo(null);
        inicializarVista();
        txtNivel.setEditable(false);
    }

    private GestionParametrosFrame() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void inicializarVista() {
        configurarTabla();
        cargarDatosAdmin();
        limpiarFormulario();
        cargarParametros();
    }

    private void configurarTabla() {
        modeloTabla = new DefaultTableModel(
                new Object[]{"Nivel", "Tiempo Base"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        tblParametros.setModel(modeloTabla);
    }

    private void cargarDatosAdmin() {
        lblTitulo.setText("Super Admin - Parámetros del Juego");
        lblAdmin.setText("Usuario: " + sesion.getNickname());
        lblEstado.setText("Estado: listo");
    }

    private void cargarParametros() {
        modeloTabla.setRowCount(0);

        List<ParametroJuego> parametros = parametroJuegoDAO.listarTodos();

        for (ParametroJuego parametro : parametros) {
            modeloTabla.addRow(new Object[]{
                parametro.getNivel(),
                parametro.getTiempoBase()
            });
        }
    }

    private void limpiarFormulario() {
        nivelSeleccionado = null;
        txtNivel.setText("");
        txtTiempoBase.setText("");
    }

    private int construirTiempoBaseDesdeFormulario() {
        if (nivelSeleccionado == null) {
            throw new RuntimeException("Selecciona un nivel.");
        }

        String tiempoTexto = txtTiempoBase.getText().trim();

        if (tiempoTexto.isEmpty()) {
            throw new RuntimeException("Ingresa el tiempo base.");
        }

        int tiempoBase;
        try {
            tiempoBase = Integer.parseInt(tiempoTexto);
        } catch (NumberFormatException e) {
            throw new RuntimeException("El tiempo base debe ser un número entero.");
        }

        if (tiempoBase <= 0) {
            throw new RuntimeException("El tiempo base debe ser mayor que 0.");
        }

        return tiempoBase;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblAdmin = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblParametros = new javax.swing.JTable();
        txtNivel = new javax.swing.JTextField();
        txtTiempoBase = new javax.swing.JTextField();
        btnLimpiarSeleccion = new javax.swing.JButton();
        btnActualizarParametro = new javax.swing.JButton();
        btnRefrescarParametros = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setText("Titulo");

        lblAdmin.setText("Admin");

        lblEstado.setText("Estado");

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tblParametros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblParametros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblParametrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblParametros);

        txtNivel.setText("Nivel");

        txtTiempoBase.setText("Tiempo Base");

        btnLimpiarSeleccion.setText("Limpiar Selección");
        btnLimpiarSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarSeleccionActionPerformed(evt);
            }
        });

        btnActualizarParametro.setText("Actualizar Parámetros");
        btnActualizarParametro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarParametroActionPerformed(evt);
            }
        });

        btnRefrescarParametros.setText("Referscar Vista");
        btnRefrescarParametros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescarParametrosActionPerformed(evt);
            }
        });

        jLabel1.setText("Nivel Seleccionado:");

        jLabel2.setText("Tiempo Base Del Nivel: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnActualizarParametro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRefrescarParametros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLimpiarSeleccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAdmin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEstado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNivel)
                            .addComponent(txtTiempoBase, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))))
                .addGap(0, 69, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(361, 361, 361)
                .addComponent(lblTitulo)
                .addGap(78, 78, 78))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRefrescarParametros)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizarParametro)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiarSeleccion))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAdmin)
                            .addComponent(txtNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEstado)
                            .addComponent(txtTiempoBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblParametrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblParametrosMouseClicked

        int fila = tblParametros.getSelectedRow();
        if (fila == -1) {
            return;
        }

        nivelSeleccionado = Integer.valueOf(tblParametros.getValueAt(fila, 0).toString());
        txtNivel.setText(tblParametros.getValueAt(fila, 0).toString());
        txtTiempoBase.setText(tblParametros.getValueAt(fila, 1).toString());

    }//GEN-LAST:event_tblParametrosMouseClicked

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void btnRefrescarParametrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarParametrosActionPerformed
        cargarParametros();
        lblEstado.setText("Estado: parámetros recargados");

    }//GEN-LAST:event_btnRefrescarParametrosActionPerformed

    private void btnActualizarParametroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarParametroActionPerformed

        try {
            int tiempoBase = construirTiempoBaseDesdeFormulario();

            boolean ok = parametroJuegoDAO.actualizarTiempoBase(nivelSeleccionado, tiempoBase);

            if (!ok) {
                throw new RuntimeException("No se pudo actualizar el parámetro.");
            }

            cargarParametros();
            lblEstado.setText("Estado: nivel " + nivelSeleccionado + " actualizado");

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_btnActualizarParametroActionPerformed

    private void btnLimpiarSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarSeleccionActionPerformed

        limpiarFormulario();
        lblEstado.setText("Estado: selección limpiada");

    }//GEN-LAST:event_btnLimpiarSeleccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionParametrosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionParametrosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionParametrosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionParametrosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionParametrosFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarParametro;
    private javax.swing.JButton btnLimpiarSeleccion;
    private javax.swing.JButton btnRefrescarParametros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblParametros;
    private javax.swing.JTextField txtNivel;
    private javax.swing.JTextField txtTiempoBase;
    // End of variables declaration//GEN-END:variables
}
