/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import dto.UsuarioSesionDTO;
import dao.PartidaDAO;
import javax.swing.JOptionPane;
import ui.JuegoFrame;
import java.util.List;
import dto.RankingJugadorDTO;
import service.JuegoService;

/**
 *
 * @author aguil
 */
public class JugadorFrame extends javax.swing.JFrame {

    private final UsuarioSesionDTO sesion;
    private final PartidaDAO partidaDAO = new PartidaDAO();
    private final JuegoService juegoService = new JuegoService();

    public JugadorFrame(UsuarioSesionDTO sesion) {
        this.sesion = sesion;
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Jugador - " + sesion.getNickname());
        lblBienvenida.setText("Bienvenido: " + sesion.getNickname() + " (" + sesion.getNombreRol() + ")");
        cargarDatosSesion();
    }

    /**
     * Creates new form JugadorFrame
     */
    public JugadorFrame() {
        this.sesion = null;
        initComponents();
        setLocationRelativeTo(null);
        cargarDatosSesion();
    }

    private void cargarDatosSesion() {
        if (sesion == null) {
            lblBienvenida.setText("Bienvenid@");
            if (lblJugador != null) {
                lblJugador.setText("Jugador: -");
            }
            if (lblSucursal != null) {
                lblSucursal.setText("Sucursal: -");
            }
            if (lblEstado != null) {
                lblEstado.setText("Estado: sin sesión");
            }
            return;
        }

        lblBienvenida.setText("Bienvenido: " + sesion.getNickname() + " (" + sesion.getNombreRol() + ")");

        if (lblJugador != null) {
            lblJugador.setText("Jugador: " + sesion.getNickname());
        }

        if (lblSucursal != null) {
            if (sesion.getIdSucursal() != null) {
                lblSucursal.setText("Sucursal ID: " + sesion.getIdSucursal());
            } else {
                lblSucursal.setText("Sucursal: no asignada");
            }
        }

        if (lblEstado != null) {
            lblEstado.setText("Estado: listo para iniciar partida");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBienvenida = new javax.swing.JLabel();
        btnIniciarPartida = new javax.swing.JButton();
        lblJugador = new javax.swing.JLabel();
        lblSucursal = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        btnVerRanking = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblBienvenida.setText("Bienvenid@ ");

        btnIniciarPartida.setText("Iniciar Partida");
        btnIniciarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarPartidaActionPerformed(evt);
            }
        });

        lblJugador.setText("Jugador");

        lblSucursal.setText("Sucursal");

        lblEstado.setText("Estado: Listo");

        btnVerRanking.setText("Ver Ranking");
        btnVerRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerRankingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(161, Short.MAX_VALUE)
                .addComponent(lblBienvenida)
                .addGap(173, 173, 173))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSucursal)
                            .addComponent(lblJugador)
                            .addComponent(lblEstado)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnIniciarPartida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVerRanking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblBienvenida)
                .addGap(18, 18, 18)
                .addComponent(lblJugador)
                .addGap(18, 18, 18)
                .addComponent(lblSucursal)
                .addGap(18, 18, 18)
                .addComponent(lblEstado)
                .addGap(18, 18, 18)
                .addComponent(btnIniciarPartida)
                .addGap(18, 18, 18)
                .addComponent(btnVerRanking)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarPartidaActionPerformed
        if (sesion == null) {
            JOptionPane.showMessageDialog(this, "No existe sesión activa.");
            return;
        }

        if (sesion.getIdSucursal() == null) {
            JOptionPane.showMessageDialog(this, "El jugador no tiene sucursal asignada.");
            return;
        }

        try {
            int idPartida = partidaDAO.crearPartida(sesion.getIdUsuario(), sesion.getIdSucursal());

            if (lblEstado != null) {
                lblEstado.setText("Estado: partida creada con ID " + idPartida);
            }

            JuegoFrame juegoFrame = new JuegoFrame(sesion, idPartida);
            juegoFrame.setVisible(true);
            this.dispose();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al iniciar partida: " + e.getMessage());
        }
     }//GEN-LAST:event_btnIniciarPartidaActionPerformed

    private void btnVerRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerRankingActionPerformed
        try {
            List<RankingJugadorDTO> ranking = juegoService.obtenerRankingGeneral(10);
            RankingFrame frame = new RankingFrame("Ranking General", ranking);
            frame.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al cargar ranking: " + e.getMessage());
        }

    }//GEN-LAST:event_btnVerRankingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JugadorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JugadorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JugadorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JugadorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JugadorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarPartida;
    private javax.swing.JButton btnVerRanking;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblJugador;
    private javax.swing.JLabel lblSucursal;
    // End of variables declaration//GEN-END:variables
}
